[project]
name = "xgboost-macos-problem"
version = "0.1.0"
description = "Reproduction of problem building standalone app on macos using Nuitka depending on xgboost"
authors = [
    {name = "David Charboneau",email = "david@mimoto.ai"}
]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "xgboost (>=2.1.4,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.group.dev.dependencies]
nuitka = { path = "../Nuitka-commercial", develop = true }
